<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FalconCanBridge.Simulators.Falcon4</RootNamespace>
    <AssemblyName>FalconCanBridge.Simulators.Falcon4</AssemblyName>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>false</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FalconCanBridge.Core\FalconCanBridge.Core.csproj" />
  </ItemGroup>

</Project>
