using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using FalconCanBridge.Core.Logging;
using FalconCanBridge.Simulators.Falcon4.Native;

namespace FalconCanBridge.Simulators.Falcon4;

/// <summary>
/// Holds the table of <see cref="Falcon4FieldDefinition"/> entries and decodes them out of a
/// raw shared-memory byte buffer into named engineering-unit values.
///
/// The default table (<see cref="BuildDefault"/>/<see cref="BuildSecondaryDefault"/>) is no
/// longer hand-typed: it's generated by <see cref="Falcon4NativeFieldMapBuilder"/> from byte-for-byte
/// vendored copies of lightningstools/F4SharedMem's <c>BMS4FlightData</c> and <c>FlightData2</c>
/// structs (see src/lightningstools in this repo, and the Native/ subfolder here), with every
/// offset computed by the .NET marshaler via <see cref="System.Runtime.InteropServices.Marshal.OffsetOf{T}(string)"/>
/// rather than guessed - see the remarks on <c>BMS4FlightDataNative</c> for why that matters. This
/// covers essentially every field BMS publishes in its two main telemetry shared-memory blocks
/// (several hundred signals), not just a hand-picked handful.
///
/// A JSON field-definitions file (config/falcon4-fields.sample.json) can still be dropped next to
/// the exe to ADD new signals or OVERRIDE individual entries (Scale/Offset/Notes/Enabled/...) of
/// the built-in table by <c>Name</c>, without recompiling - see <see cref="MergeFields"/>/
/// <see cref="MergeFromFile"/>. Use the app's Live Telemetry tab to sanity-check values against
/// known references (e.g. altitude ~0 on the runway) before trusting them on real hardware.
/// </summary>
public sealed class Falcon4FieldMap
{
    public List<Falcon4FieldDefinition> Fields { get; private set; } = new();

    public Falcon4FieldMap()
    {
        Fields = BuildDefault();
    }

    /// <summary>Creates a field map pre-loaded with an explicit field list - see <see cref="CreateSecondaryDefault"/>.</summary>
    public Falcon4FieldMap(List<Falcon4FieldDefinition> fields)
    {
        Fields = fields;
    }

    /// <summary>A field map pre-loaded with the comprehensive default table for the secondary "FalconSharedMemoryArea2" block.</summary>
    public static Falcon4FieldMap CreateSecondaryDefault() => new(BuildSecondaryDefault());

    public static Falcon4FieldMap LoadFromFile(string path)
    {
        var map = new Falcon4FieldMap();
        var loaded = LoadFieldsFromFile(path);
        if (loaded.Count > 0)
        {
            map.Fields = loaded;
        }
        return map;
    }

    /// <summary>
    /// Loads field definitions from <paramref name="path"/> and merges them onto this map's
    /// existing <see cref="Fields"/> by <see cref="Falcon4FieldDefinition.Name"/> (adds new names,
    /// overrides matching existing ones) - use this to extend/override the comprehensive built-in
    /// table from JSON without recompiling, instead of replacing it wholesale.
    /// </summary>
    public void MergeFromFile(string path) => MergeFields(LoadFieldsFromFile(path));

    public void MergeFields(IEnumerable<Falcon4FieldDefinition> extra)
    {
        var byName = Fields.ToDictionary(f => f.Name, f => f);
        int added = 0, overridden = 0;
        foreach (var f in extra)
        {
            if (byName.ContainsKey(f.Name)) overridden++; else added++;
            byName[f.Name] = f;
        }
        Fields = byName.Values.ToList();
        AppLog.Info("Falcon4", $"Merged field overrides: {added} added, {overridden} overridden (table now has {Fields.Count} fields).");
    }

    private static List<Falcon4FieldDefinition> LoadFieldsFromFile(string path)
    {
        string json = File.ReadAllText(path);
        var options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            Converters = { new JsonStringEnumConverter() }
        };
        return JsonSerializer.Deserialize<List<Falcon4FieldDefinition>>(json, options) ?? new List<Falcon4FieldDefinition>();
    }

    public static void SaveToFile(string path, List<Falcon4FieldDefinition> fields)
    {
        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            Converters = { new JsonStringEnumConverter() }
        };
        File.WriteAllText(path, JsonSerializer.Serialize(fields, options));
    }

    /// <summary>Decodes every configured field out of <paramref name="raw"/> into a name-&gt;value dictionary.</summary>
    public Dictionary<string, double> Decode(ReadOnlySpan<byte> raw)
    {
        var result = new Dictionary<string, double>(Fields.Count);

        foreach (var f in Fields)
        {
            if (f.ByteOffset < 0 || f.ByteOffset >= raw.Length) continue;

            double rawValue = f.Type switch
            {
                Falcon4FieldType.Float32 when f.ByteOffset + 4 <= raw.Length
                    => BitConverter.ToSingle(raw.Slice(f.ByteOffset, 4)),
                Falcon4FieldType.Int32 when f.ByteOffset + 4 <= raw.Length
                    => BitConverter.ToInt32(raw.Slice(f.ByteOffset, 4)),
                Falcon4FieldType.UInt32 when f.ByteOffset + 4 <= raw.Length
                    => BitConverter.ToUInt32(raw.Slice(f.ByteOffset, 4)),
                Falcon4FieldType.Int16 when f.ByteOffset + 2 <= raw.Length
                    => BitConverter.ToInt16(raw.Slice(f.ByteOffset, 2)),
                Falcon4FieldType.UInt16 when f.ByteOffset + 2 <= raw.Length
                    => BitConverter.ToUInt16(raw.Slice(f.ByteOffset, 2)),
                Falcon4FieldType.Byte
                    => raw[f.ByteOffset],
                Falcon4FieldType.SByte
                    => unchecked((sbyte)raw[f.ByteOffset]),
                Falcon4FieldType.Bit
                    => (raw[f.ByteOffset] & (1 << Math.Clamp(f.BitIndex, 0, 7))) != 0 ? 1.0 : 0.0,
                _ => 0.0
            };

            result[f.Name] = rawValue * f.Scale + f.Offset;
        }

        return result;
    }

    /// <summary>
    /// Comprehensive default field table for the primary "FalconSharedMemoryArea" block (BMS's
    /// <c>BMS4FlightData</c> struct) - every scalar field, every RWR contact slot, and every named
    /// light/HSI status bit. Generated from a vendored copy of lightningstools/F4SharedMem's own
    /// struct definitions - see <see cref="Falcon4NativeFieldMapBuilder"/>.
    /// </summary>
    public static List<Falcon4FieldDefinition> BuildDefault() => Falcon4NativeFieldMapBuilder.BuildPrimaryFields();

    /// <summary>
    /// Comprehensive default field table for the secondary "FalconSharedMemoryArea2" block (BMS's
    /// <c>FlightData2</c> struct) - decodes against a *separate* buffer from the primary block (see
    /// <see cref="Falcon4Connector"/>), not the same one <see cref="BuildDefault"/> targets.
    /// </summary>
    public static List<Falcon4FieldDefinition> BuildSecondaryDefault() => Falcon4NativeFieldMapBuilder.BuildSecondaryFields();
}
